theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

logo: https://github.com/cncf/artwork/raw/main/projects/xregistry/icon/color/xregistry-icon-color.svg
image: https://github.com/cncf/artwork/raw/main/projects/xregistry/horizontal/color/xregistry-horizontal-color.svg
title: xRegistry
description: The Extensible Registry

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
# https://github.com/pages-themes/architect
